name: IG Extractor & MEGA Upload

on:
  workflow_dispatch: 

jobs:
  extract-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: pip install requests

      - name: Create Directories
        run: |
          sudo mkdir -p /data/IG_Scraping/datasets
          sudo chown -R $USER:$USER /data

      - name: Install Rclone
        run: curl https://rclone.org/install.sh | sudo bash

      - name: Configure Rclone (Secure)
        # Is line se password aur email kabi logs mein nahi aayenge
        run: |
          rclone config create vfx mega user "${{ secrets.MEGA_USER }}" pass "${{ secrets.MEGA_PASS }}"

      - name: Sync Inputs from MEGA
        # Is se poora folder download ho jayega, file ka naam bar bar change nahi karna parega
        run: |
          echo "Syncing all JSONs from MEGA..."
          rclone copy "vfx:/Instagram_Data/Batch_2026-04-05T23-23-17/" "/data/IG_Scraping/datasets/" -P

      - name: Run Extraction Script
        run: python uni.py

      - name: Upload Results
        run: |
          echo "Uploading to MEGA..."
          rclone copy "/data/IG_Scraping" "vfx:/Instagram_Extracted_Results" -P --transfers 32
